// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/G-Core/gcorelabs-storage-sdk-go/swagger/models"
)

// KeyListHTTPV2Reader is a Reader for the KeyListHTTPV2 structure.
type KeyListHTTPV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KeyListHTTPV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKeyListHTTPV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewKeyListHTTPV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewKeyListHTTPV2OK creates a KeyListHTTPV2OK with default headers values
func NewKeyListHTTPV2OK() *KeyListHTTPV2OK {
	return &KeyListHTTPV2OK{}
}

/* KeyListHTTPV2OK describes a response with status code 200, with default header values.

Key
*/
type KeyListHTTPV2OK struct {
	Payload []*models.Key
}

func (o *KeyListHTTPV2OK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v2/key][%d] keyListHttpV2OK  %+v", 200, o.Payload)
}
func (o *KeyListHTTPV2OK) GetPayload() []*models.Key {
	return o.Payload
}

func (o *KeyListHTTPV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKeyListHTTPV2BadRequest creates a KeyListHTTPV2BadRequest with default headers values
func NewKeyListHTTPV2BadRequest() *KeyListHTTPV2BadRequest {
	return &KeyListHTTPV2BadRequest{}
}

/* KeyListHTTPV2BadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type KeyListHTTPV2BadRequest struct {
	Payload *models.ErrResponse
}

func (o *KeyListHTTPV2BadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v2/key][%d] keyListHttpV2BadRequest  %+v", 400, o.Payload)
}
func (o *KeyListHTTPV2BadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *KeyListHTTPV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
