// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKeyCreateHTTPParams creates a new KeyCreateHTTPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKeyCreateHTTPParams() *KeyCreateHTTPParams {
	return &KeyCreateHTTPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKeyCreateHTTPParamsWithTimeout creates a new KeyCreateHTTPParams object
// with the ability to set a timeout on a request.
func NewKeyCreateHTTPParamsWithTimeout(timeout time.Duration) *KeyCreateHTTPParams {
	return &KeyCreateHTTPParams{
		timeout: timeout,
	}
}

// NewKeyCreateHTTPParamsWithContext creates a new KeyCreateHTTPParams object
// with the ability to set a context for a request.
func NewKeyCreateHTTPParamsWithContext(ctx context.Context) *KeyCreateHTTPParams {
	return &KeyCreateHTTPParams{
		Context: ctx,
	}
}

// NewKeyCreateHTTPParamsWithHTTPClient creates a new KeyCreateHTTPParams object
// with the ability to set a custom HTTPClient for a request.
func NewKeyCreateHTTPParamsWithHTTPClient(client *http.Client) *KeyCreateHTTPParams {
	return &KeyCreateHTTPParams{
		HTTPClient: client,
	}
}

/* KeyCreateHTTPParams contains all the parameters to send to the API endpoint
   for the key create Http operation.

   Typically these are written to a http.Request.
*/
type KeyCreateHTTPParams struct {

	// Body.
	Body KeyCreateHTTPBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the key create Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KeyCreateHTTPParams) WithDefaults() *KeyCreateHTTPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the key create Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KeyCreateHTTPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the key create Http params
func (o *KeyCreateHTTPParams) WithTimeout(timeout time.Duration) *KeyCreateHTTPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the key create Http params
func (o *KeyCreateHTTPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the key create Http params
func (o *KeyCreateHTTPParams) WithContext(ctx context.Context) *KeyCreateHTTPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the key create Http params
func (o *KeyCreateHTTPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the key create Http params
func (o *KeyCreateHTTPParams) WithHTTPClient(client *http.Client) *KeyCreateHTTPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the key create Http params
func (o *KeyCreateHTTPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the key create Http params
func (o *KeyCreateHTTPParams) WithBody(body KeyCreateHTTPBody) *KeyCreateHTTPParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the key create Http params
func (o *KeyCreateHTTPParams) SetBody(body KeyCreateHTTPBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *KeyCreateHTTPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
