// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/G-Core/gcorelabs-storage-sdk-go/swagger/models"
)

// NewEventDeleteHTTPParams creates a new EventDeleteHTTPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEventDeleteHTTPParams() *EventDeleteHTTPParams {
	return &EventDeleteHTTPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEventDeleteHTTPParamsWithTimeout creates a new EventDeleteHTTPParams object
// with the ability to set a timeout on a request.
func NewEventDeleteHTTPParamsWithTimeout(timeout time.Duration) *EventDeleteHTTPParams {
	return &EventDeleteHTTPParams{
		timeout: timeout,
	}
}

// NewEventDeleteHTTPParamsWithContext creates a new EventDeleteHTTPParams object
// with the ability to set a context for a request.
func NewEventDeleteHTTPParamsWithContext(ctx context.Context) *EventDeleteHTTPParams {
	return &EventDeleteHTTPParams{
		Context: ctx,
	}
}

// NewEventDeleteHTTPParamsWithHTTPClient creates a new EventDeleteHTTPParams object
// with the ability to set a custom HTTPClient for a request.
func NewEventDeleteHTTPParamsWithHTTPClient(client *http.Client) *EventDeleteHTTPParams {
	return &EventDeleteHTTPParams{
		HTTPClient: client,
	}
}

/* EventDeleteHTTPParams contains all the parameters to send to the API endpoint
   for the event delete Http operation.

   Typically these are written to a http.Request.
*/
type EventDeleteHTTPParams struct {

	// Body.
	Body *models.Event

	/* ClientID.

	   ClientID who events we will get

	   Format: int64
	*/
	ClientID *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the event delete Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EventDeleteHTTPParams) WithDefaults() *EventDeleteHTTPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the event delete Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EventDeleteHTTPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the event delete Http params
func (o *EventDeleteHTTPParams) WithTimeout(timeout time.Duration) *EventDeleteHTTPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the event delete Http params
func (o *EventDeleteHTTPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the event delete Http params
func (o *EventDeleteHTTPParams) WithContext(ctx context.Context) *EventDeleteHTTPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the event delete Http params
func (o *EventDeleteHTTPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the event delete Http params
func (o *EventDeleteHTTPParams) WithHTTPClient(client *http.Client) *EventDeleteHTTPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the event delete Http params
func (o *EventDeleteHTTPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the event delete Http params
func (o *EventDeleteHTTPParams) WithBody(body *models.Event) *EventDeleteHTTPParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the event delete Http params
func (o *EventDeleteHTTPParams) SetBody(body *models.Event) {
	o.Body = body
}

// WithClientID adds the clientID to the event delete Http params
func (o *EventDeleteHTTPParams) WithClientID(clientID *int64) *EventDeleteHTTPParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the event delete Http params
func (o *EventDeleteHTTPParams) SetClientID(clientID *int64) {
	o.ClientID = clientID
}

// WriteToRequest writes these params to a swagger request
func (o *EventDeleteHTTPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.ClientID != nil {

		// query param client_id
		var qrClientID int64

		if o.ClientID != nil {
			qrClientID = *o.ClientID
		}
		qClientID := swag.FormatInt64(qrClientID)
		if qClientID != "" {

			if err := r.SetQueryParam("client_id", qClientID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
