// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/G-Core/gcorelabs-storage-sdk-go/swagger/models"
)

// EventsMetaHTTPReader is a Reader for the EventsMetaHTTP structure.
type EventsMetaHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EventsMetaHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEventsMetaHTTPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEventsMetaHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewEventsMetaHTTPUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewEventsMetaHTTPConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEventsMetaHTTPOK creates a EventsMetaHTTPOK with default headers values
func NewEventsMetaHTTPOK() *EventsMetaHTTPOK {
	return &EventsMetaHTTPOK{}
}

/* EventsMetaHTTPOK describes a response with status code 200, with default header values.

EventsMetaResponse
*/
type EventsMetaHTTPOK struct {
	Payload *models.EventsMeta
}

func (o *EventsMetaHTTPOK) Error() string {
	return fmt.Sprintf("[GET /notifications/v1/events/configurator][%d] eventsMetaHttpOK  %+v", 200, o.Payload)
}
func (o *EventsMetaHTTPOK) GetPayload() *models.EventsMeta {
	return o.Payload
}

func (o *EventsMetaHTTPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EventsMeta)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEventsMetaHTTPBadRequest creates a EventsMetaHTTPBadRequest with default headers values
func NewEventsMetaHTTPBadRequest() *EventsMetaHTTPBadRequest {
	return &EventsMetaHTTPBadRequest{}
}

/* EventsMetaHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type EventsMetaHTTPBadRequest struct {
	Payload *models.ErrResponse
}

func (o *EventsMetaHTTPBadRequest) Error() string {
	return fmt.Sprintf("[GET /notifications/v1/events/configurator][%d] eventsMetaHttpBadRequest  %+v", 400, o.Payload)
}
func (o *EventsMetaHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *EventsMetaHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEventsMetaHTTPUnauthorized creates a EventsMetaHTTPUnauthorized with default headers values
func NewEventsMetaHTTPUnauthorized() *EventsMetaHTTPUnauthorized {
	return &EventsMetaHTTPUnauthorized{}
}

/* EventsMetaHTTPUnauthorized describes a response with status code 401, with default header values.

ErrResponse
*/
type EventsMetaHTTPUnauthorized struct {
	Payload *models.ErrResponse
}

func (o *EventsMetaHTTPUnauthorized) Error() string {
	return fmt.Sprintf("[GET /notifications/v1/events/configurator][%d] eventsMetaHttpUnauthorized  %+v", 401, o.Payload)
}
func (o *EventsMetaHTTPUnauthorized) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *EventsMetaHTTPUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEventsMetaHTTPConflict creates a EventsMetaHTTPConflict with default headers values
func NewEventsMetaHTTPConflict() *EventsMetaHTTPConflict {
	return &EventsMetaHTTPConflict{}
}

/* EventsMetaHTTPConflict describes a response with status code 409, with default header values.

ErrResponse
*/
type EventsMetaHTTPConflict struct {
	Payload *models.ErrResponse
}

func (o *EventsMetaHTTPConflict) Error() string {
	return fmt.Sprintf("[GET /notifications/v1/events/configurator][%d] eventsMetaHttpConflict  %+v", 409, o.Payload)
}
func (o *EventsMetaHTTPConflict) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *EventsMetaHTTPConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
