// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEventsCreateHTTPParams creates a new EventsCreateHTTPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEventsCreateHTTPParams() *EventsCreateHTTPParams {
	return &EventsCreateHTTPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEventsCreateHTTPParamsWithTimeout creates a new EventsCreateHTTPParams object
// with the ability to set a timeout on a request.
func NewEventsCreateHTTPParamsWithTimeout(timeout time.Duration) *EventsCreateHTTPParams {
	return &EventsCreateHTTPParams{
		timeout: timeout,
	}
}

// NewEventsCreateHTTPParamsWithContext creates a new EventsCreateHTTPParams object
// with the ability to set a context for a request.
func NewEventsCreateHTTPParamsWithContext(ctx context.Context) *EventsCreateHTTPParams {
	return &EventsCreateHTTPParams{
		Context: ctx,
	}
}

// NewEventsCreateHTTPParamsWithHTTPClient creates a new EventsCreateHTTPParams object
// with the ability to set a custom HTTPClient for a request.
func NewEventsCreateHTTPParamsWithHTTPClient(client *http.Client) *EventsCreateHTTPParams {
	return &EventsCreateHTTPParams{
		HTTPClient: client,
	}
}

/* EventsCreateHTTPParams contains all the parameters to send to the API endpoint
   for the events create Http operation.

   Typically these are written to a http.Request.
*/
type EventsCreateHTTPParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the events create Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EventsCreateHTTPParams) WithDefaults() *EventsCreateHTTPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the events create Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EventsCreateHTTPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the events create Http params
func (o *EventsCreateHTTPParams) WithTimeout(timeout time.Duration) *EventsCreateHTTPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the events create Http params
func (o *EventsCreateHTTPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the events create Http params
func (o *EventsCreateHTTPParams) WithContext(ctx context.Context) *EventsCreateHTTPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the events create Http params
func (o *EventsCreateHTTPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the events create Http params
func (o *EventsCreateHTTPParams) WithHTTPClient(client *http.Client) *EventsCreateHTTPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the events create Http params
func (o *EventsCreateHTTPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *EventsCreateHTTPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
