// Code generated by go-swagger; DO NOT EDIT.

package statistics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new statistics API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for statistics API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	StorageUsageSeriesHTTPPost(params *StorageUsageSeriesHTTPPostParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageUsageSeriesHTTPPostOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  StorageUsageSeriesHTTPPost storages usage series

  Shows storage usage data in series format filtered by clients, storages and interval
*/
func (a *Client) StorageUsageSeriesHTTPPost(params *StorageUsageSeriesHTTPPostParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageUsageSeriesHTTPPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageUsageSeriesHTTPPostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageUsageSeriesHttpPost",
		Method:             "POST",
		PathPattern:        "/stats/v1/storage/usage/series",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageUsageSeriesHTTPPostReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageUsageSeriesHTTPPostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageUsageSeriesHttpPost: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
