// Code generated by go-swagger; DO NOT EDIT.

package statistics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStorageUsageSeriesHTTPPostParams creates a new StorageUsageSeriesHTTPPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStorageUsageSeriesHTTPPostParams() *StorageUsageSeriesHTTPPostParams {
	return &StorageUsageSeriesHTTPPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStorageUsageSeriesHTTPPostParamsWithTimeout creates a new StorageUsageSeriesHTTPPostParams object
// with the ability to set a timeout on a request.
func NewStorageUsageSeriesHTTPPostParamsWithTimeout(timeout time.Duration) *StorageUsageSeriesHTTPPostParams {
	return &StorageUsageSeriesHTTPPostParams{
		timeout: timeout,
	}
}

// NewStorageUsageSeriesHTTPPostParamsWithContext creates a new StorageUsageSeriesHTTPPostParams object
// with the ability to set a context for a request.
func NewStorageUsageSeriesHTTPPostParamsWithContext(ctx context.Context) *StorageUsageSeriesHTTPPostParams {
	return &StorageUsageSeriesHTTPPostParams{
		Context: ctx,
	}
}

// NewStorageUsageSeriesHTTPPostParamsWithHTTPClient creates a new StorageUsageSeriesHTTPPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewStorageUsageSeriesHTTPPostParamsWithHTTPClient(client *http.Client) *StorageUsageSeriesHTTPPostParams {
	return &StorageUsageSeriesHTTPPostParams{
		HTTPClient: client,
	}
}

/* StorageUsageSeriesHTTPPostParams contains all the parameters to send to the API endpoint
   for the storage usage series Http post operation.

   Typically these are written to a http.Request.
*/
type StorageUsageSeriesHTTPPostParams struct {

	// Body.
	Body StorageUsageSeriesHTTPPostBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the storage usage series Http post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageUsageSeriesHTTPPostParams) WithDefaults() *StorageUsageSeriesHTTPPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the storage usage series Http post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageUsageSeriesHTTPPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the storage usage series Http post params
func (o *StorageUsageSeriesHTTPPostParams) WithTimeout(timeout time.Duration) *StorageUsageSeriesHTTPPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage usage series Http post params
func (o *StorageUsageSeriesHTTPPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage usage series Http post params
func (o *StorageUsageSeriesHTTPPostParams) WithContext(ctx context.Context) *StorageUsageSeriesHTTPPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage usage series Http post params
func (o *StorageUsageSeriesHTTPPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage usage series Http post params
func (o *StorageUsageSeriesHTTPPostParams) WithHTTPClient(client *http.Client) *StorageUsageSeriesHTTPPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage usage series Http post params
func (o *StorageUsageSeriesHTTPPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the storage usage series Http post params
func (o *StorageUsageSeriesHTTPPostParams) WithBody(body StorageUsageSeriesHTTPPostBody) *StorageUsageSeriesHTTPPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the storage usage series Http post params
func (o *StorageUsageSeriesHTTPPostParams) SetBody(body StorageUsageSeriesHTTPPostBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *StorageUsageSeriesHTTPPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
