// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BucketAndStorageName bucket and storage name
//
// swagger:model BucketAndStorageName
type BucketAndStorageName struct {

	// bucket name
	BucketName string `json:"bucket_name,omitempty"`

	// storage name
	StorageName string `json:"storage_name,omitempty"`

	// UUID
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this bucket and storage name
func (m *BucketAndStorageName) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this bucket and storage name based on context it is used
func (m *BucketAndStorageName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BucketAndStorageName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BucketAndStorageName) UnmarshalBinary(b []byte) error {
	var res BucketAndStorageName
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
