// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ClientStats client stats
//
// swagger:model ClientStats
type ClientStats struct {

	// Id
	ID int64 `json:"id,omitempty"`

	// locations
	Locations map[string]LocationStats `json:"locations,omitempty"`

	// requests in sum
	RequestsInSum uint64 `json:"requests_in_sum,omitempty"`

	// requests out edges sum
	RequestsOutEdgesSum uint64 `json:"requests_out_edges_sum,omitempty"`

	// requests out wo edges sum
	RequestsOutWoEdgesSum uint64 `json:"requests_out_wo_edges_sum,omitempty"`

	// requests sum
	RequestsSum uint64 `json:"requests_sum,omitempty"`

	// size sum max
	SizeSumMax uint64 `json:"size_sum_max,omitempty"`

	// size sum mean
	SizeSumMean uint64 `json:"size_sum_mean,omitempty"`

	// traffic in sum
	TrafficInSum uint64 `json:"traffic_in_sum,omitempty"`

	// traffic out edges sum
	TrafficOutEdgesSum uint64 `json:"traffic_out_edges_sum,omitempty"`

	// traffic out wo edges sum
	TrafficOutWoEdgesSum uint64 `json:"traffic_out_wo_edges_sum,omitempty"`

	// traffic sum
	TrafficSum uint64 `json:"traffic_sum,omitempty"`
}

// Validate validates this client stats
func (m *ClientStats) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClientStats) validateLocations(formats strfmt.Registry) error {
	if swag.IsZero(m.Locations) { // not required
		return nil
	}

	for k := range m.Locations {

		if err := validate.Required("locations"+"."+k, "body", m.Locations[k]); err != nil {
			return err
		}
		if val, ok := m.Locations[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this client stats based on the context it is used
func (m *ClientStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLocations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClientStats) contextValidateLocations(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Locations {

		if val, ok := m.Locations[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClientStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClientStats) UnmarshalBinary(b []byte) error {
	var res ClientStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
