// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DataMeta Provide meta info through layers
//
// swagger:model DataMeta
type DataMeta struct {

	// to meta
	ToMeta map[string]interface{} `json:"ToMeta,omitempty"`
}

// Validate validates this data meta
func (m *DataMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this data meta based on context it is used
func (m *DataMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataMeta) UnmarshalBinary(b []byte) error {
	var res DataMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
