// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EventsMeta EventsMeta describe how to form POST/PATCH request
//
// swagger:model EventsMeta
type EventsMeta struct {

	// Structure of request body
	Structure []*EventDescription `json:"structure"`

	// example
	Example *Events `json:"example,omitempty"`
}

// Validate validates this events meta
func (m *EventsMeta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStructure(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExample(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventsMeta) validateStructure(formats strfmt.Registry) error {
	if swag.IsZero(m.Structure) { // not required
		return nil
	}

	for i := 0; i < len(m.Structure); i++ {
		if swag.IsZero(m.Structure[i]) { // not required
			continue
		}

		if m.Structure[i] != nil {
			if err := m.Structure[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("structure" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("structure" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EventsMeta) validateExample(formats strfmt.Registry) error {
	if swag.IsZero(m.Example) { // not required
		return nil
	}

	if m.Example != nil {
		if err := m.Example.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("example")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("example")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this events meta based on the context it is used
func (m *EventsMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStructure(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExample(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventsMeta) contextValidateStructure(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Structure); i++ {

		if m.Structure[i] != nil {
			if err := m.Structure[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("structure" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("structure" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EventsMeta) contextValidateExample(ctx context.Context, formats strfmt.Registry) error {

	if m.Example != nil {
		if err := m.Example.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("example")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("example")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EventsMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventsMeta) UnmarshalBinary(b []byte) error {
	var res EventsMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
