// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LimitByBytes limit by bytes
//
// swagger:model LimitByBytes
type LimitByBytes struct {

	// bucket name
	BucketName string `json:"bucket_name,omitempty"`

	// bytes
	Bytes uint64 `json:"bytes,omitempty"`

	// storage name
	StorageName string `json:"storage_name,omitempty"`

	// UUID
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this limit by bytes
func (m *LimitByBytes) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this limit by bytes based on context it is used
func (m *LimitByBytes) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LimitByBytes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LimitByBytes) UnmarshalBinary(b []byte) error {
	var res LimitByBytes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
