// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StatsMetrics stats metrics
//
// swagger:model StatsMetrics
type StatsMetrics struct {

	// requests in sum
	RequestsInSum uint64 `json:"requests_in_sum,omitempty"`

	// requests out edges sum
	RequestsOutEdgesSum uint64 `json:"requests_out_edges_sum,omitempty"`

	// requests out wo edges sum
	RequestsOutWoEdgesSum uint64 `json:"requests_out_wo_edges_sum,omitempty"`

	// requests sum
	RequestsSum uint64 `json:"requests_sum,omitempty"`

	// size sum max
	SizeSumMax uint64 `json:"size_sum_max,omitempty"`

	// size sum mean
	SizeSumMean uint64 `json:"size_sum_mean,omitempty"`

	// traffic in sum
	TrafficInSum uint64 `json:"traffic_in_sum,omitempty"`

	// traffic out edges sum
	TrafficOutEdgesSum uint64 `json:"traffic_out_edges_sum,omitempty"`

	// traffic out wo edges sum
	TrafficOutWoEdgesSum uint64 `json:"traffic_out_wo_edges_sum,omitempty"`

	// traffic sum
	TrafficSum uint64 `json:"traffic_sum,omitempty"`
}

// Validate validates this stats metrics
func (m *StatsMetrics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stats metrics based on context it is used
func (m *StatsMetrics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StatsMetrics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StatsMetrics) UnmarshalBinary(b []byte) error {
	var res StatsMetrics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
