// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageStats storage stats
//
// swagger:model StorageStats
type StorageStats struct {

	// name
	Name string `json:"name,omitempty"`

	// requests in series
	RequestsInSeries [][]interface{} `json:"requests_in_series"`

	// requests in sum
	RequestsInSum uint64 `json:"requests_in_sum,omitempty"`

	// requests out edges series
	RequestsOutEdgesSeries [][]interface{} `json:"requests_out_edges_series"`

	// requests out edges sum
	RequestsOutEdgesSum uint64 `json:"requests_out_edges_sum,omitempty"`

	// requests out wo edges series
	RequestsOutWoEdgesSeries [][]interface{} `json:"requests_out_wo_edges_series"`

	// requests out wo edges sum
	RequestsOutWoEdgesSum uint64 `json:"requests_out_wo_edges_sum,omitempty"`

	// requests series
	RequestsSeries [][]interface{} `json:"requests_series"`

	// requests sum
	RequestsSum uint64 `json:"requests_sum,omitempty"`

	// size max series
	SizeMaxSeries [][]interface{} `json:"size_max_series"`

	// size mean
	SizeMean [][]interface{} `json:"size_mean_series"`

	// size sum max
	SizeSumMax uint64 `json:"size_sum_max,omitempty"`

	// size sum mean
	SizeSumMean uint64 `json:"size_sum_mean,omitempty"`

	// traffic in series
	TrafficInSeries [][]interface{} `json:"traffic_in_series"`

	// traffic in sum
	TrafficInSum uint64 `json:"traffic_in_sum,omitempty"`

	// traffic out edges series
	TrafficOutEdgesSeries [][]interface{} `json:"traffic_out_edges_series"`

	// traffic out edges sum
	TrafficOutEdgesSum uint64 `json:"traffic_out_edges_sum,omitempty"`

	// traffic out wo edges series
	TrafficOutWoEdgesSeries [][]interface{} `json:"traffic_out_wo_edges_series"`

	// traffic out wo edges sum
	TrafficOutWoEdgesSum uint64 `json:"traffic_out_wo_edges_sum,omitempty"`

	// traffic series
	TrafficSeries [][]interface{} `json:"traffic_series"`

	// traffic sum
	TrafficSum uint64 `json:"traffic_sum,omitempty"`
}

// Validate validates this storage stats
func (m *StorageStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage stats based on context it is used
func (m *StorageStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorageStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageStats) UnmarshalBinary(b []byte) error {
	var res StorageStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
