// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageStats storage stats
//
// swagger:model StorageStats
type StorageStats struct {

	// a BucketsSeries is max bucket files count for grouped period {name:[[timestamp, count]]}
	// Example: {"bucketA":[[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]}
	BucketsSeries map[string][][]interface{} `json:"buckets_series,omitempty"`

	// a FileQuantitySumMax is max sum of files quantity for grouped period
	FileQuantitySumMax uint64 `json:"file_quantity_sum_max,omitempty"`

	// a Name of storage
	Name string `json:"name,omitempty"`

	// a RequestsInSeries is sum of incoming requests for grouped period [[timestamp, count]]
	// Example: [[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]
	RequestsInSeries [][]interface{} `json:"requests_in_series"`

	// a RequestsInSum is sum of incoming  requests for grouped period
	RequestsInSum uint64 `json:"requests_in_sum,omitempty"`

	// a RequestsOutWoEdgesSeries is sum of out requests (only edges) for grouped period [[timestamp, count]]
	// Example: [[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]
	RequestsOutEdgesSeries [][]interface{} `json:"requests_out_edges_series"`

	// a RequestsOutEdgesSum is sum of out edges requests for grouped period
	RequestsOutEdgesSum uint64 `json:"requests_out_edges_sum,omitempty"`

	// a RequestsOutWoEdgesSeries is sum of out requests (without edges) for grouped period [[timestamp, count]]
	// Example: [[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]
	RequestsOutWoEdgesSeries [][]interface{} `json:"requests_out_wo_edges_series"`

	// a RequestsOutWoEdgesSum is sum of out no edges requests for grouped period
	RequestsOutWoEdgesSum uint64 `json:"requests_out_wo_edges_sum,omitempty"`

	// a RequestsSeries is sum of out requests for grouped period [[timestamp, count]]
	// Example: [[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]
	RequestsSeries [][]interface{} `json:"requests_series"`

	// a RequestsSum is sum of all requests for grouped period
	RequestsSum uint64 `json:"requests_sum,omitempty"`

	// a SizeMaxSeries is max of files size for grouped period [[timestamp, count]]
	// Example: [[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]
	SizeMaxSeries [][]interface{} `json:"size_max_series"`

	// a SizeMean is mean of files size for grouped period [[timestamp, count]]
	// Example: [[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]
	SizeMean [][]interface{} `json:"size_mean_series"`

	// a SizeSumMax is max sum of all files sizes for grouped period
	SizeSumMax uint64 `json:"size_sum_max,omitempty"`

	// a SizeSumMean is mean sum of all files sizes for grouped period
	SizeSumMean uint64 `json:"size_sum_mean,omitempty"`

	// a TrafficInSeries is sum of incoming traffic bytes for grouped period [[timestamp, count]]
	// Example: [[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]
	TrafficInSeries [][]interface{} `json:"traffic_in_series"`

	// a TrafficInSum is sum of incoming  traffic for grouped period
	TrafficInSum uint64 `json:"traffic_in_sum,omitempty"`

	// a TrafficOutWoEdgesSeries is sum of out traffic bytes (only edges) for grouped period [[timestamp, count]]
	// Example: [[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]
	TrafficOutEdgesSeries [][]interface{} `json:"traffic_out_edges_series"`

	// a TrafficOutEdgesSum is sum of out edges traffic for grouped period
	TrafficOutEdgesSum uint64 `json:"traffic_out_edges_sum,omitempty"`

	// a TrafficOutWoEdgesSeries is sum of out traffic bytes (without edges) for grouped period [[timestamp, count]]
	// Example: [[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]
	TrafficOutWoEdgesSeries [][]interface{} `json:"traffic_out_wo_edges_series"`

	// a TrafficOutWoEdgesSum is sum of out no edges traffic for grouped period
	TrafficOutWoEdgesSum uint64 `json:"traffic_out_wo_edges_sum,omitempty"`

	// a TrafficSeries is sum of traffic bytes for grouped period [[timestamp, count]]
	// Example: [[1632748614,1],[1632748615,2],[1632748616,2],[1632748617,1]]
	TrafficSeries [][]interface{} `json:"traffic_series"`

	// a TrafficSum is sum of all traffic for grouped period
	TrafficSum uint64 `json:"traffic_sum,omitempty"`
}

// Validate validates this storage stats
func (m *StorageStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage stats based on context it is used
func (m *StorageStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorageStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageStats) UnmarshalBinary(b []byte) error {
	var res StorageStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
