// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageGetBucketCorsEndpointRes StorageGetBucketCorsEndpointRes output
//
// swagger:model StorageGetBucketCorsEndpointRes
type StorageGetBucketCorsEndpointRes struct {

	// data
	Data string `json:"data,omitempty"`
}

// Validate validates this storage get bucket cors endpoint res
func (m *StorageGetBucketCorsEndpointRes) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage get bucket cors endpoint res based on context it is used
func (m *StorageGetBucketCorsEndpointRes) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorageGetBucketCorsEndpointRes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageGetBucketCorsEndpointRes) UnmarshalBinary(b []byte) error {
	var res StorageGetBucketCorsEndpointRes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
