// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/G-Core/gcorelabs-storage-sdk-go/swagger/models"
)

// GetStorageBucketCORSHTTPReader is a Reader for the GetStorageBucketCORSHTTP structure.
type GetStorageBucketCORSHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStorageBucketCORSHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStorageBucketCORSHTTPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetStorageBucketCORSHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetStorageBucketCORSHTTPOK creates a GetStorageBucketCORSHTTPOK with default headers values
func NewGetStorageBucketCORSHTTPOK() *GetStorageBucketCORSHTTPOK {
	return &GetStorageBucketCORSHTTPOK{}
}

/* GetStorageBucketCORSHTTPOK describes a response with status code 200, with default header values.

StorageGetBucketCorsEndpointRes
*/
type GetStorageBucketCORSHTTPOK struct {
	Payload *models.StorageGetBucketCorsEndpointRes
}

func (o *GetStorageBucketCORSHTTPOK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/storage/{id}/s3/bucket/{name}/cors][%d] getStorageBucketCORSHttpOK  %+v", 200, o.Payload)
}
func (o *GetStorageBucketCORSHTTPOK) GetPayload() *models.StorageGetBucketCorsEndpointRes {
	return o.Payload
}

func (o *GetStorageBucketCORSHTTPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageGetBucketCorsEndpointRes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStorageBucketCORSHTTPBadRequest creates a GetStorageBucketCORSHTTPBadRequest with default headers values
func NewGetStorageBucketCORSHTTPBadRequest() *GetStorageBucketCORSHTTPBadRequest {
	return &GetStorageBucketCORSHTTPBadRequest{}
}

/* GetStorageBucketCORSHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type GetStorageBucketCORSHTTPBadRequest struct {
	Payload *models.ErrResponse
}

func (o *GetStorageBucketCORSHTTPBadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/storage/{id}/s3/bucket/{name}/cors][%d] getStorageBucketCORSHttpBadRequest  %+v", 400, o.Payload)
}
func (o *GetStorageBucketCORSHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *GetStorageBucketCORSHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetStorageBucketCORSHTTPBody get storage bucket c o r s HTTP body
swagger:model GetStorageBucketCORSHTTPBody
*/
type GetStorageBucketCORSHTTPBody struct {

	// allowed origins
	AllowedOrigins []string `json:"allowedOrigins"`
}

// Validate validates this get storage bucket c o r s HTTP body
func (o *GetStorageBucketCORSHTTPBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get storage bucket c o r s HTTP body based on context it is used
func (o *GetStorageBucketCORSHTTPBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetStorageBucketCORSHTTPBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetStorageBucketCORSHTTPBody) UnmarshalBinary(b []byte) error {
	var res GetStorageBucketCORSHTTPBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
