// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/G-Core/gcorelabs-storage-sdk-go/swagger/models"
)

// KeyLinkHTTPReader is a Reader for the KeyLinkHTTP structure.
type KeyLinkHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KeyLinkHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewKeyLinkHTTPNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewKeyLinkHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewKeyLinkHTTPNoContent creates a KeyLinkHTTPNoContent with default headers values
func NewKeyLinkHTTPNoContent() *KeyLinkHTTPNoContent {
	return &KeyLinkHTTPNoContent{}
}

/* KeyLinkHTTPNoContent describes a response with status code 204, with default header values.

A SuccessResponse is a response that shows that operations was completed successfully
*/
type KeyLinkHTTPNoContent struct {
}

func (o *KeyLinkHTTPNoContent) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/key/{key_id}/link][%d] keyLinkHttpNoContent ", 204)
}

func (o *KeyLinkHTTPNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewKeyLinkHTTPBadRequest creates a KeyLinkHTTPBadRequest with default headers values
func NewKeyLinkHTTPBadRequest() *KeyLinkHTTPBadRequest {
	return &KeyLinkHTTPBadRequest{}
}

/* KeyLinkHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type KeyLinkHTTPBadRequest struct {
	Payload *models.ErrResponse
}

func (o *KeyLinkHTTPBadRequest) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/key/{key_id}/link][%d] keyLinkHttpBadRequest  %+v", 400, o.Payload)
}
func (o *KeyLinkHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *KeyLinkHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
