// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/G-Core/gcore-storage-sdk-go/swagger/models"
)

// StorageListHTTPV2Reader is a Reader for the StorageListHTTPV2 structure.
type StorageListHTTPV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageListHTTPV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStorageListHTTPV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageListHTTPV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStorageListHTTPV2OK creates a StorageListHTTPV2OK with default headers values
func NewStorageListHTTPV2OK() *StorageListHTTPV2OK {
	return &StorageListHTTPV2OK{}
}

/* StorageListHTTPV2OK describes a response with status code 200, with default header values.

StorageListEndpointRes
*/
type StorageListHTTPV2OK struct {
	Payload *models.StorageListEndpointRes
}

func (o *StorageListHTTPV2OK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v2/storage][%d] storageListHttpV2OK  %+v", 200, o.Payload)
}
func (o *StorageListHTTPV2OK) GetPayload() *models.StorageListEndpointRes {
	return o.Payload
}

func (o *StorageListHTTPV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageListEndpointRes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStorageListHTTPV2BadRequest creates a StorageListHTTPV2BadRequest with default headers values
func NewStorageListHTTPV2BadRequest() *StorageListHTTPV2BadRequest {
	return &StorageListHTTPV2BadRequest{}
}

/* StorageListHTTPV2BadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageListHTTPV2BadRequest struct {
	Payload *models.ErrResponse
}

func (o *StorageListHTTPV2BadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v2/storage][%d] storageListHttpV2BadRequest  %+v", 400, o.Payload)
}
func (o *StorageListHTTPV2BadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageListHTTPV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
