// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStorageBucketRemoveHTTPParams creates a new StorageBucketRemoveHTTPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStorageBucketRemoveHTTPParams() *StorageBucketRemoveHTTPParams {
	return &StorageBucketRemoveHTTPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStorageBucketRemoveHTTPParamsWithTimeout creates a new StorageBucketRemoveHTTPParams object
// with the ability to set a timeout on a request.
func NewStorageBucketRemoveHTTPParamsWithTimeout(timeout time.Duration) *StorageBucketRemoveHTTPParams {
	return &StorageBucketRemoveHTTPParams{
		timeout: timeout,
	}
}

// NewStorageBucketRemoveHTTPParamsWithContext creates a new StorageBucketRemoveHTTPParams object
// with the ability to set a context for a request.
func NewStorageBucketRemoveHTTPParamsWithContext(ctx context.Context) *StorageBucketRemoveHTTPParams {
	return &StorageBucketRemoveHTTPParams{
		Context: ctx,
	}
}

// NewStorageBucketRemoveHTTPParamsWithHTTPClient creates a new StorageBucketRemoveHTTPParams object
// with the ability to set a custom HTTPClient for a request.
func NewStorageBucketRemoveHTTPParamsWithHTTPClient(client *http.Client) *StorageBucketRemoveHTTPParams {
	return &StorageBucketRemoveHTTPParams{
		HTTPClient: client,
	}
}

/* StorageBucketRemoveHTTPParams contains all the parameters to send to the API endpoint
   for the storage bucket remove Http operation.

   Typically these are written to a http.Request.
*/
type StorageBucketRemoveHTTPParams struct {

	// ID.
	//
	// Format: int64
	ID int64

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the storage bucket remove Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageBucketRemoveHTTPParams) WithDefaults() *StorageBucketRemoveHTTPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the storage bucket remove Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageBucketRemoveHTTPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the storage bucket remove Http params
func (o *StorageBucketRemoveHTTPParams) WithTimeout(timeout time.Duration) *StorageBucketRemoveHTTPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage bucket remove Http params
func (o *StorageBucketRemoveHTTPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage bucket remove Http params
func (o *StorageBucketRemoveHTTPParams) WithContext(ctx context.Context) *StorageBucketRemoveHTTPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage bucket remove Http params
func (o *StorageBucketRemoveHTTPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage bucket remove Http params
func (o *StorageBucketRemoveHTTPParams) WithHTTPClient(client *http.Client) *StorageBucketRemoveHTTPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage bucket remove Http params
func (o *StorageBucketRemoveHTTPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the storage bucket remove Http params
func (o *StorageBucketRemoveHTTPParams) WithID(id int64) *StorageBucketRemoveHTTPParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the storage bucket remove Http params
func (o *StorageBucketRemoveHTTPParams) SetID(id int64) {
	o.ID = id
}

// WithName adds the name to the storage bucket remove Http params
func (o *StorageBucketRemoveHTTPParams) WithName(name string) *StorageBucketRemoveHTTPParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the storage bucket remove Http params
func (o *StorageBucketRemoveHTTPParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *StorageBucketRemoveHTTPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
