// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/G-Core/gcore-storage-sdk-go/swagger/models"
)

// StorageBucketRemoveHTTPReader is a Reader for the StorageBucketRemoveHTTP structure.
type StorageBucketRemoveHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageBucketRemoveHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewStorageBucketRemoveHTTPNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageBucketRemoveHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStorageBucketRemoveHTTPNoContent creates a StorageBucketRemoveHTTPNoContent with default headers values
func NewStorageBucketRemoveHTTPNoContent() *StorageBucketRemoveHTTPNoContent {
	return &StorageBucketRemoveHTTPNoContent{}
}

/* StorageBucketRemoveHTTPNoContent describes a response with status code 204, with default header values.

A SuccessResponse is a response that shows that operations was completed successfully
*/
type StorageBucketRemoveHTTPNoContent struct {
}

func (o *StorageBucketRemoveHTTPNoContent) Error() string {
	return fmt.Sprintf("[DELETE /provisioning/v1/storage/{id}/s3/bucket/{name}][%d] storageBucketRemoveHttpNoContent ", 204)
}

func (o *StorageBucketRemoveHTTPNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStorageBucketRemoveHTTPBadRequest creates a StorageBucketRemoveHTTPBadRequest with default headers values
func NewStorageBucketRemoveHTTPBadRequest() *StorageBucketRemoveHTTPBadRequest {
	return &StorageBucketRemoveHTTPBadRequest{}
}

/* StorageBucketRemoveHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageBucketRemoveHTTPBadRequest struct {
	Payload *models.ErrResponse
}

func (o *StorageBucketRemoveHTTPBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /provisioning/v1/storage/{id}/s3/bucket/{name}][%d] storageBucketRemoveHttpBadRequest  %+v", 400, o.Payload)
}
func (o *StorageBucketRemoveHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageBucketRemoveHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
