// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStorageBucketLifecycleDeleteHTTPParams creates a new StorageBucketLifecycleDeleteHTTPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStorageBucketLifecycleDeleteHTTPParams() *StorageBucketLifecycleDeleteHTTPParams {
	return &StorageBucketLifecycleDeleteHTTPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStorageBucketLifecycleDeleteHTTPParamsWithTimeout creates a new StorageBucketLifecycleDeleteHTTPParams object
// with the ability to set a timeout on a request.
func NewStorageBucketLifecycleDeleteHTTPParamsWithTimeout(timeout time.Duration) *StorageBucketLifecycleDeleteHTTPParams {
	return &StorageBucketLifecycleDeleteHTTPParams{
		timeout: timeout,
	}
}

// NewStorageBucketLifecycleDeleteHTTPParamsWithContext creates a new StorageBucketLifecycleDeleteHTTPParams object
// with the ability to set a context for a request.
func NewStorageBucketLifecycleDeleteHTTPParamsWithContext(ctx context.Context) *StorageBucketLifecycleDeleteHTTPParams {
	return &StorageBucketLifecycleDeleteHTTPParams{
		Context: ctx,
	}
}

// NewStorageBucketLifecycleDeleteHTTPParamsWithHTTPClient creates a new StorageBucketLifecycleDeleteHTTPParams object
// with the ability to set a custom HTTPClient for a request.
func NewStorageBucketLifecycleDeleteHTTPParamsWithHTTPClient(client *http.Client) *StorageBucketLifecycleDeleteHTTPParams {
	return &StorageBucketLifecycleDeleteHTTPParams{
		HTTPClient: client,
	}
}

/* StorageBucketLifecycleDeleteHTTPParams contains all the parameters to send to the API endpoint
   for the storage bucket lifecycle delete Http operation.

   Typically these are written to a http.Request.
*/
type StorageBucketLifecycleDeleteHTTPParams struct {

	// ID.
	//
	// Format: int64
	ID int64

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the storage bucket lifecycle delete Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageBucketLifecycleDeleteHTTPParams) WithDefaults() *StorageBucketLifecycleDeleteHTTPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the storage bucket lifecycle delete Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageBucketLifecycleDeleteHTTPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the storage bucket lifecycle delete Http params
func (o *StorageBucketLifecycleDeleteHTTPParams) WithTimeout(timeout time.Duration) *StorageBucketLifecycleDeleteHTTPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage bucket lifecycle delete Http params
func (o *StorageBucketLifecycleDeleteHTTPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage bucket lifecycle delete Http params
func (o *StorageBucketLifecycleDeleteHTTPParams) WithContext(ctx context.Context) *StorageBucketLifecycleDeleteHTTPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage bucket lifecycle delete Http params
func (o *StorageBucketLifecycleDeleteHTTPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage bucket lifecycle delete Http params
func (o *StorageBucketLifecycleDeleteHTTPParams) WithHTTPClient(client *http.Client) *StorageBucketLifecycleDeleteHTTPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage bucket lifecycle delete Http params
func (o *StorageBucketLifecycleDeleteHTTPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the storage bucket lifecycle delete Http params
func (o *StorageBucketLifecycleDeleteHTTPParams) WithID(id int64) *StorageBucketLifecycleDeleteHTTPParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the storage bucket lifecycle delete Http params
func (o *StorageBucketLifecycleDeleteHTTPParams) SetID(id int64) {
	o.ID = id
}

// WithName adds the name to the storage bucket lifecycle delete Http params
func (o *StorageBucketLifecycleDeleteHTTPParams) WithName(name string) *StorageBucketLifecycleDeleteHTTPParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the storage bucket lifecycle delete Http params
func (o *StorageBucketLifecycleDeleteHTTPParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *StorageBucketLifecycleDeleteHTTPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
