// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStorageUpdateHTTPParams creates a new StorageUpdateHTTPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStorageUpdateHTTPParams() *StorageUpdateHTTPParams {
	return &StorageUpdateHTTPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStorageUpdateHTTPParamsWithTimeout creates a new StorageUpdateHTTPParams object
// with the ability to set a timeout on a request.
func NewStorageUpdateHTTPParamsWithTimeout(timeout time.Duration) *StorageUpdateHTTPParams {
	return &StorageUpdateHTTPParams{
		timeout: timeout,
	}
}

// NewStorageUpdateHTTPParamsWithContext creates a new StorageUpdateHTTPParams object
// with the ability to set a context for a request.
func NewStorageUpdateHTTPParamsWithContext(ctx context.Context) *StorageUpdateHTTPParams {
	return &StorageUpdateHTTPParams{
		Context: ctx,
	}
}

// NewStorageUpdateHTTPParamsWithHTTPClient creates a new StorageUpdateHTTPParams object
// with the ability to set a custom HTTPClient for a request.
func NewStorageUpdateHTTPParamsWithHTTPClient(client *http.Client) *StorageUpdateHTTPParams {
	return &StorageUpdateHTTPParams{
		HTTPClient: client,
	}
}

/* StorageUpdateHTTPParams contains all the parameters to send to the API endpoint
   for the storage update Http operation.

   Typically these are written to a http.Request.
*/
type StorageUpdateHTTPParams struct {

	// Body.
	Body StorageUpdateHTTPBody

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the storage update Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageUpdateHTTPParams) WithDefaults() *StorageUpdateHTTPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the storage update Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageUpdateHTTPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the storage update Http params
func (o *StorageUpdateHTTPParams) WithTimeout(timeout time.Duration) *StorageUpdateHTTPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage update Http params
func (o *StorageUpdateHTTPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage update Http params
func (o *StorageUpdateHTTPParams) WithContext(ctx context.Context) *StorageUpdateHTTPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage update Http params
func (o *StorageUpdateHTTPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage update Http params
func (o *StorageUpdateHTTPParams) WithHTTPClient(client *http.Client) *StorageUpdateHTTPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage update Http params
func (o *StorageUpdateHTTPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the storage update Http params
func (o *StorageUpdateHTTPParams) WithBody(body StorageUpdateHTTPBody) *StorageUpdateHTTPParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the storage update Http params
func (o *StorageUpdateHTTPParams) SetBody(body StorageUpdateHTTPBody) {
	o.Body = body
}

// WithID adds the id to the storage update Http params
func (o *StorageUpdateHTTPParams) WithID(id int64) *StorageUpdateHTTPParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the storage update Http params
func (o *StorageUpdateHTTPParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *StorageUpdateHTTPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
