// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new storage API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for storage API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetStorageBucketCORSHTTP(params *GetStorageBucketCORSHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetStorageBucketCORSHTTPOK, error)

	KeyLinkHTTP(params *KeyLinkHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*KeyLinkHTTPNoContent, error)

	KeyUnlinkHTTP(params *KeyUnlinkHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*KeyUnlinkHTTPNoContent, error)

	StorageBucketCORSCreateHTTP(params *StorageBucketCORSCreateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketCORSCreateHTTPNoContent, error)

	StorageBucketCreateHTTP(params *StorageBucketCreateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketCreateHTTPNoContent, error)

	StorageBucketLifecycleCreateHTTP(params *StorageBucketLifecycleCreateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketLifecycleCreateHTTPNoContent, error)

	StorageBucketLifecycleDeleteHTTP(params *StorageBucketLifecycleDeleteHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketLifecycleDeleteHTTPNoContent, error)

	StorageBucketPolicyCreateHTTP(params *StorageBucketPolicyCreateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketPolicyCreateHTTPNoContent, error)

	StorageBucketRemoveHTTP(params *StorageBucketRemoveHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketRemoveHTTPNoContent, error)

	StorageCreateHTTP(params *StorageCreateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageCreateHTTPOK, error)

	StorageDeleteHTTP(params *StorageDeleteHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageDeleteHTTPNoContent, error)

	StorageGetHTTP(params *StorageGetHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageGetHTTPOK, error)

	StorageListBucketsHTTP(params *StorageListBucketsHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageListBucketsHTTPOK, error)

	StorageListHTTPV1(params *StorageListHTTPV1Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageListHTTPV1OK, error)

	StorageListHTTPV2(params *StorageListHTTPV2Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageListHTTPV2OK, error)

	StorageUpdateCredentialsHTTP(params *StorageUpdateCredentialsHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageUpdateCredentialsHTTPOK, error)

	StorageUpdateHTTP(params *StorageUpdateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageUpdateHTTPOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetStorageBucketCORSHTTP gets s3 storage bucket cors

  Get s3 storage bucket cors
*/
func (a *Client) GetStorageBucketCORSHTTP(params *GetStorageBucketCORSHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetStorageBucketCORSHTTPOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetStorageBucketCORSHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getStorageBucketCORSHttp",
		Method:             "GET",
		PathPattern:        "/provisioning/v1/storage/{id}/s3/bucket/{name}/cors",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetStorageBucketCORSHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetStorageBucketCORSHTTPOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getStorageBucketCORSHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  KeyLinkHTTP links key to storage

  Link key to storage
*/
func (a *Client) KeyLinkHTTP(params *KeyLinkHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*KeyLinkHTTPNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewKeyLinkHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "keyLinkHttp",
		Method:             "POST",
		PathPattern:        "/provisioning/v1/storage/{id}/key/{key_id}/link",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &KeyLinkHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*KeyLinkHTTPNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for keyLinkHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  KeyUnlinkHTTP unlinks key from storage

  Unlink key from storage
*/
func (a *Client) KeyUnlinkHTTP(params *KeyUnlinkHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*KeyUnlinkHTTPNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewKeyUnlinkHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "keyUnlinkHttp",
		Method:             "POST",
		PathPattern:        "/provisioning/v1/storage/{id}/key/{key_id}/unlink",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &KeyUnlinkHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*KeyUnlinkHTTPNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for keyUnlinkHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageBucketCORSCreateHTTP creates s3 storage bucket cors

  Create s3 storage bucket cors
*/
func (a *Client) StorageBucketCORSCreateHTTP(params *StorageBucketCORSCreateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketCORSCreateHTTPNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageBucketCORSCreateHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageBucketCORSCreateHttp",
		Method:             "POST",
		PathPattern:        "/provisioning/v1/storage/{id}/s3/bucket/{name}/cors",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageBucketCORSCreateHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageBucketCORSCreateHTTPNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageBucketCORSCreateHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageBucketCreateHTTP creates s3 storage bucket

  Create s3 storage bucket
*/
func (a *Client) StorageBucketCreateHTTP(params *StorageBucketCreateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketCreateHTTPNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageBucketCreateHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageBucketCreateHttp",
		Method:             "POST",
		PathPattern:        "/provisioning/v1/storage/{id}/s3/bucket/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageBucketCreateHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageBucketCreateHTTPNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageBucketCreateHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageBucketLifecycleCreateHTTP creates s3 storage bucket lifecycle

  Create s3 storage bucket lifecycle
*/
func (a *Client) StorageBucketLifecycleCreateHTTP(params *StorageBucketLifecycleCreateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketLifecycleCreateHTTPNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageBucketLifecycleCreateHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageBucketLifecycleCreateHttp",
		Method:             "POST",
		PathPattern:        "/provisioning/v1/storage/{id}/s3/bucket/{name}/lifecycle",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageBucketLifecycleCreateHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageBucketLifecycleCreateHTTPNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageBucketLifecycleCreateHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageBucketLifecycleDeleteHTTP deletes s3 storage bucket lifecycle

  Delete s3 storage bucket lifecycle
*/
func (a *Client) StorageBucketLifecycleDeleteHTTP(params *StorageBucketLifecycleDeleteHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketLifecycleDeleteHTTPNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageBucketLifecycleDeleteHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageBucketLifecycleDeleteHttp",
		Method:             "DELETE",
		PathPattern:        "/provisioning/v1/storage/{id}/s3/bucket/{name}/lifecycle",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageBucketLifecycleDeleteHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageBucketLifecycleDeleteHTTPNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageBucketLifecycleDeleteHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageBucketPolicyCreateHTTP creates s3 storage bucket policy

  Create s3 storage bucket policy
*/
func (a *Client) StorageBucketPolicyCreateHTTP(params *StorageBucketPolicyCreateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketPolicyCreateHTTPNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageBucketPolicyCreateHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageBucketPolicyCreateHttp",
		Method:             "POST",
		PathPattern:        "/provisioning/v1/storage/{id}/s3/bucket/{name}/policy",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageBucketPolicyCreateHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageBucketPolicyCreateHTTPNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageBucketPolicyCreateHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageBucketRemoveHTTP removes s3 storage bucket

  Remove s3 storage bucket
*/
func (a *Client) StorageBucketRemoveHTTP(params *StorageBucketRemoveHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageBucketRemoveHTTPNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageBucketRemoveHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageBucketRemoveHttp",
		Method:             "DELETE",
		PathPattern:        "/provisioning/v1/storage/{id}/s3/bucket/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageBucketRemoveHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageBucketRemoveHTTPNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageBucketRemoveHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageCreateHTTP creates storage

  Creates storage and returns it
*/
func (a *Client) StorageCreateHTTP(params *StorageCreateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageCreateHTTPOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageCreateHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageCreateHttp",
		Method:             "PUT",
		PathPattern:        "/provisioning/v1/storage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageCreateHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageCreateHTTPOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageCreateHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageDeleteHTTP deletes storage

  Delete storage
*/
func (a *Client) StorageDeleteHTTP(params *StorageDeleteHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageDeleteHTTPNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageDeleteHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageDeleteHttp",
		Method:             "DELETE",
		PathPattern:        "/provisioning/v1/storage/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageDeleteHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageDeleteHTTPNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageDeleteHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageGetHTTP gets storage

  Get storage
*/
func (a *Client) StorageGetHTTP(params *StorageGetHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageGetHTTPOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageGetHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageGetHttp",
		Method:             "GET",
		PathPattern:        "/provisioning/v1/storage/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageGetHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageGetHTTPOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageGetHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageListBucketsHTTP lists s3 storage buckets

  List s3 storage buckets
*/
func (a *Client) StorageListBucketsHTTP(params *StorageListBucketsHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageListBucketsHTTPOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageListBucketsHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageListBucketsHttp",
		Method:             "GET",
		PathPattern:        "/provisioning/v1/storage/{id}/s3/buckets",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageListBucketsHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageListBucketsHTTPOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageListBucketsHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageListHTTPV1 lists storages

  List storages
*/
func (a *Client) StorageListHTTPV1(params *StorageListHTTPV1Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageListHTTPV1OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageListHTTPV1Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageListHttpV1",
		Method:             "GET",
		PathPattern:        "/provisioning/v1/storage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageListHTTPV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageListHTTPV1OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageListHttpV1: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageListHTTPV2 lists storages v2

  List storages v2
*/
func (a *Client) StorageListHTTPV2(params *StorageListHTTPV2Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageListHTTPV2OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageListHTTPV2Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageListHttpV2",
		Method:             "GET",
		PathPattern:        "/provisioning/v2/storage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageListHTTPV2Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageListHTTPV2OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageListHttpV2: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageUpdateCredentialsHTTP resets storage credentials

  Reset storage credentials
*/
func (a *Client) StorageUpdateCredentialsHTTP(params *StorageUpdateCredentialsHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageUpdateCredentialsHTTPOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageUpdateCredentialsHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageUpdateCredentialsHttp",
		Method:             "POST",
		PathPattern:        "/provisioning/v1/storage/{id}/credentials",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageUpdateCredentialsHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageUpdateCredentialsHTTPOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageUpdateCredentialsHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StorageUpdateHTTP updates storage

  Updates storage and returns it
*/
func (a *Client) StorageUpdateHTTP(params *StorageUpdateHTTPParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StorageUpdateHTTPOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageUpdateHTTPParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "storageUpdateHttp",
		Method:             "POST",
		PathPattern:        "/provisioning/v1/storage/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StorageUpdateHTTPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageUpdateHTTPOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for storageUpdateHttp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
