// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/G-Core/gcorelabs-storage-sdk-go/swagger/models"
)

// StorageDeleteHTTPReader is a Reader for the StorageDeleteHTTP structure.
type StorageDeleteHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageDeleteHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewStorageDeleteHTTPNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageDeleteHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStorageDeleteHTTPNoContent creates a StorageDeleteHTTPNoContent with default headers values
func NewStorageDeleteHTTPNoContent() *StorageDeleteHTTPNoContent {
	return &StorageDeleteHTTPNoContent{}
}

/* StorageDeleteHTTPNoContent describes a response with status code 204, with default header values.

A SuccessResponse is a response that shows that operations was completed successfully
*/
type StorageDeleteHTTPNoContent struct {
}

func (o *StorageDeleteHTTPNoContent) Error() string {
	return fmt.Sprintf("[DELETE /provisioning/v1/storage/{id}][%d] storageDeleteHttpNoContent ", 204)
}

func (o *StorageDeleteHTTPNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStorageDeleteHTTPBadRequest creates a StorageDeleteHTTPBadRequest with default headers values
func NewStorageDeleteHTTPBadRequest() *StorageDeleteHTTPBadRequest {
	return &StorageDeleteHTTPBadRequest{}
}

/* StorageDeleteHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageDeleteHTTPBadRequest struct {
	Payload *models.ErrResponse
}

func (o *StorageDeleteHTTPBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /provisioning/v1/storage/{id}][%d] storageDeleteHttpBadRequest  %+v", 400, o.Payload)
}
func (o *StorageDeleteHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageDeleteHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
