// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/G-Core/gcorelabs-storage-sdk-go/swagger/models"
)

// StorageListBucketsHTTPReader is a Reader for the StorageListBucketsHTTP structure.
type StorageListBucketsHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageListBucketsHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStorageListBucketsHTTPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageListBucketsHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStorageListBucketsHTTPOK creates a StorageListBucketsHTTPOK with default headers values
func NewStorageListBucketsHTTPOK() *StorageListBucketsHTTPOK {
	return &StorageListBucketsHTTPOK{}
}

/* StorageListBucketsHTTPOK describes a response with status code 200, with default header values.

StorageListBucketsEndpointRes
*/
type StorageListBucketsHTTPOK struct {
	Payload *models.StorageListBucketsEndpointRes
}

func (o *StorageListBucketsHTTPOK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/storage/{id}/s3/buckets][%d] storageListBucketsHttpOK  %+v", 200, o.Payload)
}
func (o *StorageListBucketsHTTPOK) GetPayload() *models.StorageListBucketsEndpointRes {
	return o.Payload
}

func (o *StorageListBucketsHTTPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageListBucketsEndpointRes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStorageListBucketsHTTPBadRequest creates a StorageListBucketsHTTPBadRequest with default headers values
func NewStorageListBucketsHTTPBadRequest() *StorageListBucketsHTTPBadRequest {
	return &StorageListBucketsHTTPBadRequest{}
}

/* StorageListBucketsHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageListBucketsHTTPBadRequest struct {
	Payload *models.ErrResponse
}

func (o *StorageListBucketsHTTPBadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/storage/{id}/s3/buckets][%d] storageListBucketsHttpBadRequest  %+v", 400, o.Payload)
}
func (o *StorageListBucketsHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageListBucketsHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
