// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStorageDeleteHTTPParams creates a new StorageDeleteHTTPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStorageDeleteHTTPParams() *StorageDeleteHTTPParams {
	return &StorageDeleteHTTPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStorageDeleteHTTPParamsWithTimeout creates a new StorageDeleteHTTPParams object
// with the ability to set a timeout on a request.
func NewStorageDeleteHTTPParamsWithTimeout(timeout time.Duration) *StorageDeleteHTTPParams {
	return &StorageDeleteHTTPParams{
		timeout: timeout,
	}
}

// NewStorageDeleteHTTPParamsWithContext creates a new StorageDeleteHTTPParams object
// with the ability to set a context for a request.
func NewStorageDeleteHTTPParamsWithContext(ctx context.Context) *StorageDeleteHTTPParams {
	return &StorageDeleteHTTPParams{
		Context: ctx,
	}
}

// NewStorageDeleteHTTPParamsWithHTTPClient creates a new StorageDeleteHTTPParams object
// with the ability to set a custom HTTPClient for a request.
func NewStorageDeleteHTTPParamsWithHTTPClient(client *http.Client) *StorageDeleteHTTPParams {
	return &StorageDeleteHTTPParams{
		HTTPClient: client,
	}
}

/* StorageDeleteHTTPParams contains all the parameters to send to the API endpoint
   for the storage delete Http operation.

   Typically these are written to a http.Request.
*/
type StorageDeleteHTTPParams struct {

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the storage delete Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageDeleteHTTPParams) WithDefaults() *StorageDeleteHTTPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the storage delete Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageDeleteHTTPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the storage delete Http params
func (o *StorageDeleteHTTPParams) WithTimeout(timeout time.Duration) *StorageDeleteHTTPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage delete Http params
func (o *StorageDeleteHTTPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage delete Http params
func (o *StorageDeleteHTTPParams) WithContext(ctx context.Context) *StorageDeleteHTTPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage delete Http params
func (o *StorageDeleteHTTPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage delete Http params
func (o *StorageDeleteHTTPParams) WithHTTPClient(client *http.Client) *StorageDeleteHTTPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage delete Http params
func (o *StorageDeleteHTTPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the storage delete Http params
func (o *StorageDeleteHTTPParams) WithID(id int64) *StorageDeleteHTTPParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the storage delete Http params
func (o *StorageDeleteHTTPParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *StorageDeleteHTTPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
