// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/G-Core/gcore-storage-sdk-go/swagger/models"
)

// StorageBucketCreateHTTPReader is a Reader for the StorageBucketCreateHTTP structure.
type StorageBucketCreateHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageBucketCreateHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewStorageBucketCreateHTTPNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageBucketCreateHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStorageBucketCreateHTTPNoContent creates a StorageBucketCreateHTTPNoContent with default headers values
func NewStorageBucketCreateHTTPNoContent() *StorageBucketCreateHTTPNoContent {
	return &StorageBucketCreateHTTPNoContent{}
}

/* StorageBucketCreateHTTPNoContent describes a response with status code 204, with default header values.

A SuccessResponse is a response that shows that operations was completed successfully
*/
type StorageBucketCreateHTTPNoContent struct {
}

func (o *StorageBucketCreateHTTPNoContent) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/s3/bucket/{name}][%d] storageBucketCreateHttpNoContent ", 204)
}

func (o *StorageBucketCreateHTTPNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStorageBucketCreateHTTPBadRequest creates a StorageBucketCreateHTTPBadRequest with default headers values
func NewStorageBucketCreateHTTPBadRequest() *StorageBucketCreateHTTPBadRequest {
	return &StorageBucketCreateHTTPBadRequest{}
}

/* StorageBucketCreateHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageBucketCreateHTTPBadRequest struct {
	Payload *models.ErrResponse
}

func (o *StorageBucketCreateHTTPBadRequest) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/s3/bucket/{name}][%d] storageBucketCreateHttpBadRequest  %+v", 400, o.Payload)
}
func (o *StorageBucketCreateHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageBucketCreateHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
