// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/G-Core/gcorelabs-storage-sdk-go/swagger/models"
)

// StorageBucketLifecycleCreateHTTPReader is a Reader for the StorageBucketLifecycleCreateHTTP structure.
type StorageBucketLifecycleCreateHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageBucketLifecycleCreateHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewStorageBucketLifecycleCreateHTTPNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageBucketLifecycleCreateHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStorageBucketLifecycleCreateHTTPNoContent creates a StorageBucketLifecycleCreateHTTPNoContent with default headers values
func NewStorageBucketLifecycleCreateHTTPNoContent() *StorageBucketLifecycleCreateHTTPNoContent {
	return &StorageBucketLifecycleCreateHTTPNoContent{}
}

/* StorageBucketLifecycleCreateHTTPNoContent describes a response with status code 204, with default header values.

A SuccessResponse is a response that shows that operations was completed successfully
*/
type StorageBucketLifecycleCreateHTTPNoContent struct {
}

func (o *StorageBucketLifecycleCreateHTTPNoContent) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/s3/bucket/{name}/lifecycle][%d] storageBucketLifecycleCreateHttpNoContent ", 204)
}

func (o *StorageBucketLifecycleCreateHTTPNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStorageBucketLifecycleCreateHTTPBadRequest creates a StorageBucketLifecycleCreateHTTPBadRequest with default headers values
func NewStorageBucketLifecycleCreateHTTPBadRequest() *StorageBucketLifecycleCreateHTTPBadRequest {
	return &StorageBucketLifecycleCreateHTTPBadRequest{}
}

/* StorageBucketLifecycleCreateHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageBucketLifecycleCreateHTTPBadRequest struct {
	Payload *models.ErrResponse
}

func (o *StorageBucketLifecycleCreateHTTPBadRequest) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/s3/bucket/{name}/lifecycle][%d] storageBucketLifecycleCreateHttpBadRequest  %+v", 400, o.Payload)
}
func (o *StorageBucketLifecycleCreateHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageBucketLifecycleCreateHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*StorageBucketLifecycleCreateHTTPBody storage bucket lifecycle create HTTP body
swagger:model StorageBucketLifecycleCreateHTTPBody
*/
type StorageBucketLifecycleCreateHTTPBody struct {

	// expiration days
	ExpirationDays int64 `json:"expiration_days,omitempty"`
}

// Validate validates this storage bucket lifecycle create HTTP body
func (o *StorageBucketLifecycleCreateHTTPBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage bucket lifecycle create HTTP body based on context it is used
func (o *StorageBucketLifecycleCreateHTTPBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *StorageBucketLifecycleCreateHTTPBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *StorageBucketLifecycleCreateHTTPBody) UnmarshalBinary(b []byte) error {
	var res StorageBucketLifecycleCreateHTTPBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
