// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStorageBucketLifecycleCreateHTTPParams creates a new StorageBucketLifecycleCreateHTTPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStorageBucketLifecycleCreateHTTPParams() *StorageBucketLifecycleCreateHTTPParams {
	return &StorageBucketLifecycleCreateHTTPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStorageBucketLifecycleCreateHTTPParamsWithTimeout creates a new StorageBucketLifecycleCreateHTTPParams object
// with the ability to set a timeout on a request.
func NewStorageBucketLifecycleCreateHTTPParamsWithTimeout(timeout time.Duration) *StorageBucketLifecycleCreateHTTPParams {
	return &StorageBucketLifecycleCreateHTTPParams{
		timeout: timeout,
	}
}

// NewStorageBucketLifecycleCreateHTTPParamsWithContext creates a new StorageBucketLifecycleCreateHTTPParams object
// with the ability to set a context for a request.
func NewStorageBucketLifecycleCreateHTTPParamsWithContext(ctx context.Context) *StorageBucketLifecycleCreateHTTPParams {
	return &StorageBucketLifecycleCreateHTTPParams{
		Context: ctx,
	}
}

// NewStorageBucketLifecycleCreateHTTPParamsWithHTTPClient creates a new StorageBucketLifecycleCreateHTTPParams object
// with the ability to set a custom HTTPClient for a request.
func NewStorageBucketLifecycleCreateHTTPParamsWithHTTPClient(client *http.Client) *StorageBucketLifecycleCreateHTTPParams {
	return &StorageBucketLifecycleCreateHTTPParams{
		HTTPClient: client,
	}
}

/* StorageBucketLifecycleCreateHTTPParams contains all the parameters to send to the API endpoint
   for the storage bucket lifecycle create Http operation.

   Typically these are written to a http.Request.
*/
type StorageBucketLifecycleCreateHTTPParams struct {

	// Body.
	Body StorageBucketLifecycleCreateHTTPBody

	// ID.
	//
	// Format: int64
	ID int64

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the storage bucket lifecycle create Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageBucketLifecycleCreateHTTPParams) WithDefaults() *StorageBucketLifecycleCreateHTTPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the storage bucket lifecycle create Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageBucketLifecycleCreateHTTPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) WithTimeout(timeout time.Duration) *StorageBucketLifecycleCreateHTTPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) WithContext(ctx context.Context) *StorageBucketLifecycleCreateHTTPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) WithHTTPClient(client *http.Client) *StorageBucketLifecycleCreateHTTPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) WithBody(body StorageBucketLifecycleCreateHTTPBody) *StorageBucketLifecycleCreateHTTPParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) SetBody(body StorageBucketLifecycleCreateHTTPBody) {
	o.Body = body
}

// WithID adds the id to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) WithID(id int64) *StorageBucketLifecycleCreateHTTPParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) SetID(id int64) {
	o.ID = id
}

// WithName adds the name to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) WithName(name string) *StorageBucketLifecycleCreateHTTPParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the storage bucket lifecycle create Http params
func (o *StorageBucketLifecycleCreateHTTPParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *StorageBucketLifecycleCreateHTTPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
