// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStorageCreateHTTPParams creates a new StorageCreateHTTPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStorageCreateHTTPParams() *StorageCreateHTTPParams {
	return &StorageCreateHTTPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStorageCreateHTTPParamsWithTimeout creates a new StorageCreateHTTPParams object
// with the ability to set a timeout on a request.
func NewStorageCreateHTTPParamsWithTimeout(timeout time.Duration) *StorageCreateHTTPParams {
	return &StorageCreateHTTPParams{
		timeout: timeout,
	}
}

// NewStorageCreateHTTPParamsWithContext creates a new StorageCreateHTTPParams object
// with the ability to set a context for a request.
func NewStorageCreateHTTPParamsWithContext(ctx context.Context) *StorageCreateHTTPParams {
	return &StorageCreateHTTPParams{
		Context: ctx,
	}
}

// NewStorageCreateHTTPParamsWithHTTPClient creates a new StorageCreateHTTPParams object
// with the ability to set a custom HTTPClient for a request.
func NewStorageCreateHTTPParamsWithHTTPClient(client *http.Client) *StorageCreateHTTPParams {
	return &StorageCreateHTTPParams{
		HTTPClient: client,
	}
}

/* StorageCreateHTTPParams contains all the parameters to send to the API endpoint
   for the storage create Http operation.

   Typically these are written to a http.Request.
*/
type StorageCreateHTTPParams struct {

	// Body.
	Body StorageCreateHTTPBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the storage create Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageCreateHTTPParams) WithDefaults() *StorageCreateHTTPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the storage create Http params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageCreateHTTPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the storage create Http params
func (o *StorageCreateHTTPParams) WithTimeout(timeout time.Duration) *StorageCreateHTTPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage create Http params
func (o *StorageCreateHTTPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage create Http params
func (o *StorageCreateHTTPParams) WithContext(ctx context.Context) *StorageCreateHTTPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage create Http params
func (o *StorageCreateHTTPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage create Http params
func (o *StorageCreateHTTPParams) WithHTTPClient(client *http.Client) *StorageCreateHTTPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage create Http params
func (o *StorageCreateHTTPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the storage create Http params
func (o *StorageCreateHTTPParams) WithBody(body StorageCreateHTTPBody) *StorageCreateHTTPParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the storage create Http params
func (o *StorageCreateHTTPParams) SetBody(body StorageCreateHTTPBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *StorageCreateHTTPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
