// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/G-Core/gcorelabs-storage-sdk-go/swagger/models"
)

// StorageUpdateCredentialsHTTPReader is a Reader for the StorageUpdateCredentialsHTTP structure.
type StorageUpdateCredentialsHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageUpdateCredentialsHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStorageUpdateCredentialsHTTPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageUpdateCredentialsHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStorageUpdateCredentialsHTTPOK creates a StorageUpdateCredentialsHTTPOK with default headers values
func NewStorageUpdateCredentialsHTTPOK() *StorageUpdateCredentialsHTTPOK {
	return &StorageUpdateCredentialsHTTPOK{}
}

/* StorageUpdateCredentialsHTTPOK describes a response with status code 200, with default header values.

Storage
*/
type StorageUpdateCredentialsHTTPOK struct {
	Payload *models.Storage
}

func (o *StorageUpdateCredentialsHTTPOK) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/credentials][%d] storageUpdateCredentialsHttpOK  %+v", 200, o.Payload)
}
func (o *StorageUpdateCredentialsHTTPOK) GetPayload() *models.Storage {
	return o.Payload
}

func (o *StorageUpdateCredentialsHTTPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Storage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStorageUpdateCredentialsHTTPBadRequest creates a StorageUpdateCredentialsHTTPBadRequest with default headers values
func NewStorageUpdateCredentialsHTTPBadRequest() *StorageUpdateCredentialsHTTPBadRequest {
	return &StorageUpdateCredentialsHTTPBadRequest{}
}

/* StorageUpdateCredentialsHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageUpdateCredentialsHTTPBadRequest struct {
	Payload *models.ErrResponse
}

func (o *StorageUpdateCredentialsHTTPBadRequest) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/credentials][%d] storageUpdateCredentialsHttpBadRequest  %+v", 400, o.Payload)
}
func (o *StorageUpdateCredentialsHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageUpdateCredentialsHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*StorageUpdateCredentialsHTTPBody storage update credentials HTTP body
swagger:model StorageUpdateCredentialsHTTPBody
*/
type StorageUpdateCredentialsHTTPBody struct {

	// delete sftp password
	DeleteSftpPassword bool `json:"delete_sftp_password,omitempty"`

	// generate s3 keys
	GenerateS3Keys bool `json:"generate_s3_keys,omitempty"`

	// generate sftp password
	GenerateSftpPassword bool `json:"generate_sftp_password,omitempty"`

	// reset sftp keys
	ResetSftpKeys bool `json:"reset_sftp_keys,omitempty"`

	// sftp password
	SftpPassword string `json:"sftp_password,omitempty"`
}

// Validate validates this storage update credentials HTTP body
func (o *StorageUpdateCredentialsHTTPBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage update credentials HTTP body based on context it is used
func (o *StorageUpdateCredentialsHTTPBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *StorageUpdateCredentialsHTTPBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *StorageUpdateCredentialsHTTPBody) UnmarshalBinary(b []byte) error {
	var res StorageUpdateCredentialsHTTPBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
